import React from "react";
import {
  Info,
  Layers,
  BarChart2,
  CheckCircle2,
  Circle,
  Loader2,
  AlertTriangle,
  Brain,
  FlaskConical,
  Activity,
  ScanLine,
  ShieldCheck,
} from "lucide-react";
import { AnalysisResult, TopPrediction } from "../types";

// ============================================================
// Types
// ============================================================

interface AnalysisResultsProps {
  result: AnalysisResult | null;
  xrayUrl: string;
  heatmapUrl: string;
  shapUrl: string;
  isLoading: boolean;
  loadingStep: number;
}

// ============================================================
// Helpers
// ============================================================

function getConfidenceBadge(prob: number): { label: string; color: string; dot: string } {
  if (prob >= 70) return { label: "High Confidence", color: "bg-emerald-100 text-emerald-700", dot: "🟢" };
  if (prob >= 30) return { label: "Moderate", color: "bg-amber-100 text-amber-700", dot: "🟡" };
  return { label: "Low Probability", color: "bg-slate-100 text-slate-500", dot: "⚪" };
}

function getBarColor(prob: number): string {
  if (prob >= 70) return "bg-emerald-500";
  if (prob >= 30) return "bg-amber-500";
  return "bg-slate-400";
}

function generateClinicalSummary(result: AnalysisResult): string {
  const top = result.top_predictions[0];
  const second = result.top_predictions[1];
  const topConf = top?.probability?.toFixed(2) ?? "N/A";
  const topDisease = top?.disease ?? "Unknown";
  const secondDisease = second?.disease;

  let summary = `The multimodal attention model predicts "${topDisease}" as the primary finding with a confidence of ${topConf}%. `;

  if (secondDisease && secondDisease !== topDisease) {
    summary += `A secondary differential of "${secondDisease}" was also noted at ${second.probability.toFixed(2)}% confidence. `;
  }

  summary += `The Grad-CAM visualization highlights the spatial regions of the X-ray that contributed most strongly to this classification. `;
  summary += `SHAP analysis indicates that patient age exerted the highest influence among the provided clinical metadata features, followed by view position and gender. `;
  summary += `These findings are generated by an attention-enhanced multimodal CNN and should be interpreted as decision-support information. `;
  summary += `Review by a qualified radiologist or clinician is strongly recommended before any clinical action.`;

  return summary;
}

// ============================================================
// Loading Stepper
// ============================================================

const LOADING_STEPS = [
  { id: 1, label: "Uploading X-ray", icon: <ScanLine className="w-4 h-4" /> },
  { id: 2, label: "Running Prediction", icon: <Brain className="w-4 h-4" /> },
  { id: 3, label: "Generating Grad-CAM", icon: <Activity className="w-4 h-4" /> },
  { id: 4, label: "Generating SHAP", icon: <BarChart2 className="w-4 h-4" /> },
  { id: 5, label: "Preparing Clinical Summary", icon: <FlaskConical className="w-4 h-4" /> },
];

function LoadingStepper({ currentStep }: { currentStep: number }) {
  return (
    <section
      id="results-section"
      className="max-w-7xl mx-auto px-6 md:px-12 py-16 bg-surface-container-low rounded-[40px] my-12"
    >
      <div className="flex flex-col items-center gap-8 text-center">
        <div className="space-y-1">
          <p className="font-heading text-2xl font-bold text-on-surface">
            Analyzing Patient Data
          </p>
          <p className="text-sm text-secondary max-w-md">
            Multimodal attention fusion pipeline is running. This may take 20–60 seconds.
          </p>
        </div>

        <div className="w-full max-w-sm space-y-3">
          {LOADING_STEPS.map((step) => {
            const isDone = currentStep > step.id;
            const isActive = currentStep === step.id;
            return (
              <div
                key={step.id}
                className={`flex items-center gap-3 px-4 py-3 rounded-2xl border transition-all duration-500 ${
                  isDone
                    ? "border-emerald-200 bg-emerald-50"
                    : isActive
                    ? "border-primary/30 bg-primary/5"
                    : "border-outline-variant bg-surface-container-lowest opacity-40"
                }`}
              >
                <span
                  className={`${
                    isDone ? "text-emerald-500" : isActive ? "text-primary" : "text-secondary"
                  }`}
                >
                  {isDone ? (
                    <CheckCircle2 className="w-5 h-5" />
                  ) : isActive ? (
                    <Loader2 className="w-5 h-5 animate-spin" />
                  ) : (
                    <Circle className="w-5 h-5" />
                  )}
                </span>
                <span
                  className={`text-sm font-semibold ${
                    isDone ? "text-emerald-700" : isActive ? "text-on-surface" : "text-secondary"
                  }`}
                >
                  {step.label}
                </span>
                {isDone && (
                  <span className="ml-auto text-xs text-emerald-500 font-medium">Done</span>
                )}
                {isActive && (
                  <span className="ml-auto text-xs text-primary font-medium animate-pulse">
                    Running…
                  </span>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

// ============================================================
// Prediction Card
// ============================================================

function PredictionCard({ prediction, rank }: { key?: React.Key; prediction: TopPrediction; rank: number }) {
  const badge = getConfidenceBadge(prediction.probability);
  const barColor = getBarColor(prediction.probability);

  return (
    <div className="p-4 bg-surface-container rounded-2xl border border-outline-variant space-y-3">
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2">
          <span className="w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center flex-shrink-0">
            {rank}
          </span>
          <span className="font-sans text-sm font-bold text-on-surface leading-tight">
            {prediction.disease}
          </span>
        </div>
        <span className="font-mono text-base font-bold text-primary flex-shrink-0">
          {prediction.probability.toFixed(2)}%
        </span>
      </div>

      <div className="w-full bg-surface-container-low rounded-full h-2.5 overflow-hidden">
        <div
          className={`h-full ${barColor} rounded-full transition-all duration-1000 ease-out`}
          style={{ width: `${Math.min(prediction.probability, 100)}%` }}
        />
      </div>

      <div className="flex items-center gap-1.5">
        <span className="text-xs">{badge.dot}</span>
        <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${badge.color}`}>
          {badge.label}
        </span>
      </div>
    </div>
  );
}

// ============================================================
// Diagnostic Confidence Card
// ============================================================

function DiagnosticConfidenceCard({ result }: { result: AnalysisResult }) {
  const top = result.top_predictions[0];
  const totalDiseases = Object.keys(result.predictions).length;

  return (
    <div className="bg-surface-container-lowest border border-outline-variant rounded-3xl p-6 shadow-soft">
      <h4 className="font-heading text-sm font-bold text-secondary uppercase tracking-wider mb-4">
        Diagnostic Summary
      </h4>
      <div className="grid grid-cols-2 gap-4">
        <div>
          <p className="text-xs text-secondary mb-1">Top Prediction</p>
          <p className="font-bold text-on-surface text-sm">{top?.disease ?? "—"}</p>
        </div>
        <div>
          <p className="text-xs text-secondary mb-1">Confidence</p>
          <p className="font-mono font-bold text-primary text-sm">{top?.probability?.toFixed(2) ?? "—"}%</p>
        </div>
        <div>
          <p className="text-xs text-secondary mb-1">Diseases Evaluated</p>
          <p className="font-bold text-on-surface text-sm">{totalDiseases}</p>
        </div>
        <div>
          <p className="text-xs text-secondary mb-1">Inference</p>
          <p className="font-bold text-on-surface text-sm leading-tight">Attention-Enhanced Multimodal CNN</p>
        </div>
      </div>
    </div>
  );
}

// ============================================================
// Main Component
// ============================================================

export default function AnalysisResults({
  result,
  xrayUrl,
  heatmapUrl,
  shapUrl,
  isLoading,
  loadingStep,
}: AnalysisResultsProps) {

  if (isLoading) {
    return <LoadingStepper currentStep={loadingStep} />;
  }

  if (!result) {
    return (
      <div className="max-w-7xl mx-auto px-6 md:px-12 py-8 text-center text-secondary border border-dashed border-outline-variant rounded-3xl my-6">
        <Info className="w-8 h-8 mx-auto mb-2 opacity-60" />
        <p className="text-sm font-medium">
          Please select clinical attributes and click 'Analyze Patient' to calculate prediction weights.
        </p>
      </div>
    );
  }

  const topPrediction = result.top_predictions[0];
  const clinicalSummary = generateClinicalSummary(result);

  return (
    <section
      id="results-section"
      className="max-w-7xl mx-auto px-6 md:px-12 py-12 bg-surface-container-low rounded-[40px] my-12 scroll-mt-20"
    >
      {/* ── Header ─────────────────────────────────────── */}
      <div className="mb-10">
        <h2 className="font-heading text-2xl sm:text-3xl font-bold text-on-surface flex items-center gap-2">
          <span>📊</span> Analysis Results
        </h2>
        <p className="font-sans text-sm text-secondary mt-1">
          Multimodal Attention Fusion · Grad-CAM Interpretability · SHAP Metadata Analysis
        </p>
      </div>

      {/* ── Row 1: Predictions + Diagnostic Card ────────── */}
      <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 mb-6">

        {/* Left: Prediction Cards */}
        <div className="xl:col-span-5 bg-surface-container-lowest p-6 rounded-3xl shadow-soft border border-outline-variant flex flex-col gap-4">
          <h4 className="font-heading text-lg font-bold text-on-surface flex items-center gap-2">
            <Layers className="w-5 h-5 text-primary" />
            Top Predicted Pathologies
          </h4>
          <div className="space-y-3">
            {result.top_predictions.map((prediction, i) => (
              <PredictionCard key={prediction.disease} prediction={prediction} rank={i + 1} />
            ))}
          </div>
          <div className="mt-auto pt-2">
            <DiagnosticConfidenceCard result={result} />
          </div>
        </div>

        {/* Right: Grad-CAM Visualization */}
        <div className="xl:col-span-7 bg-surface-container-lowest p-6 rounded-3xl shadow-soft border border-outline-variant flex flex-col gap-5">
          <div className="flex justify-between items-start gap-4 flex-wrap">
            <div>
              <h4 className="font-heading text-lg font-bold text-on-surface">
                Interpretability: Grad-CAM Visualization
              </h4>
              <p className="text-xs text-secondary mt-1">
                Saliency maps indicating vision stream network focus areas
              </p>
            </div>
            <span className="bg-secondary-fixed text-on-secondary-fixed-variant px-3 py-1 rounded-full font-sans text-xs font-semibold">
              Global Average Pooling Layer
            </span>
          </div>

          {/* Predicted disease info row */}
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-surface-container rounded-2xl px-4 py-3">
              <p className="text-xs text-secondary mb-0.5">Predicted Disease</p>
              <p className="font-bold text-on-surface text-sm">{topPrediction?.disease ?? "—"}</p>
            </div>
            <div className="bg-surface-container rounded-2xl px-4 py-3">
              <p className="text-xs text-secondary mb-0.5">Confidence</p>
              <p className="font-mono font-bold text-primary text-sm">
                {topPrediction?.probability?.toFixed(2) ?? "—"}%
              </p>
            </div>
          </div>

          {/* Images */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Original Input */}
            <div className="relative rounded-2xl overflow-hidden aspect-[4/3] border border-outline-variant shadow-sm group bg-surface-container">
              {xrayUrl ? (
                <img
                  referrerPolicy="no-referrer"
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                  alt="Chest X-Ray input"
                  src={xrayUrl}
                  onError={(e) => { (e.target as HTMLImageElement).style.display = "none"; }}
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center text-secondary text-xs">
                  Generating visualization…
                </div>
              )}
              <div className="absolute top-3 left-3 bg-inverse-surface/80 text-inverse-on-surface px-3 py-1 rounded-full text-xs font-semibold backdrop-blur-sm shadow-sm">
                Original Input
              </div>
            </div>

            {/* Attention Heatmap */}
            <div className="relative rounded-2xl overflow-hidden aspect-[4/3] border border-outline-variant shadow-sm group bg-surface-container">
              {heatmapUrl ? (
                <img
                  referrerPolicy="no-referrer"
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                  alt="Attention mapping heatmap"
                  src={heatmapUrl}
                  onError={(e) => { (e.target as HTMLImageElement).style.display = "none"; }}
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center text-secondary text-xs">
                  Generating visualization…
                </div>
              )}
              <div className="absolute top-3 left-3 bg-inverse-surface/80 text-inverse-on-surface px-3 py-1 rounded-full text-xs font-semibold backdrop-blur-sm shadow-sm">
                Attention Heatmap
              </div>
            </div>
          </div>

          {/* Heatmap legend */}
          <p className="text-xs text-secondary italic text-center">
            🔴 Red regions indicate areas that contributed most strongly to the model prediction.
          </p>
        </div>
      </div>

      {/* ── Row 2: SHAP ─────────────────────────────────── */}
      <div className="bg-surface-container-lowest p-6 rounded-3xl shadow-soft border border-outline-variant mb-6">
        <div className="flex justify-between items-start gap-4 flex-wrap mb-6">
          <div>
            <h4 className="font-heading text-lg font-bold text-on-surface flex items-center gap-2">
              <BarChart2 className="w-5 h-5 text-primary" />
              Multimodal Feature Importance (SHAP)
            </h4>
            <p className="text-xs text-secondary mt-1">
              Impact of clinical metadata attributes on model predictions
            </p>
          </div>
          <span className="bg-secondary-fixed text-on-secondary-fixed-variant px-3 py-1 rounded-full font-sans text-xs font-semibold">
            Metadata SHAP Explainer
          </span>
        </div>

        <div className="flex flex-col md:flex-row gap-6 items-start">
          {/* SHAP Plot */}
          <div className="flex-1 rounded-2xl overflow-hidden border border-outline-variant shadow-sm flex items-center justify-center bg-white p-3 min-h-[180px]">
            {shapUrl ? (
              <img
                referrerPolicy="no-referrer"
                className="max-h-[350px] w-auto object-contain rounded-lg"
                alt="SHAP Feature Importance Plot"
                src={shapUrl}
                onError={(e) => { (e.target as HTMLImageElement).style.display = "none"; }}
              />
            ) : (
              <div className="text-secondary text-xs text-center py-8">
                SHAP explanation visualization will appear here after analysis.
              </div>
            )}
          </div>

          {/* SHAP Metadata Ranking Panel */}
          <div className="md:w-56 flex-shrink-0 space-y-3">
            <h5 className="font-heading text-sm font-bold text-on-surface">
              Metadata Importance
            </h5>
            <p className="text-xs text-secondary">
              Ranked influence of clinical attributes on model output.
            </p>

            {[
              { feature: "Age", rank: "Highest influence", color: "bg-emerald-100 text-emerald-700", bar: "w-full" },
              { feature: "View Position", rank: "Moderate influence", color: "bg-amber-100 text-amber-700", bar: "w-2/3" },
              { feature: "Gender", rank: "Minimal influence", color: "bg-slate-100 text-slate-500", bar: "w-1/3" },
            ].map((item) => (
              <div key={item.feature} className="p-3 rounded-xl bg-surface-container border border-outline-variant space-y-1.5">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-on-surface">{item.feature}</span>
                  <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${item.color}`}>
                    {item.rank}
                  </span>
                </div>
                <div className="w-full h-1.5 bg-surface-container-low rounded-full">
                  <div className={`h-full ${item.bar} rounded-full bg-primary transition-all duration-700`} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── Row 3: AI Clinical Interpretation ───────────── */}
      <div className="bg-surface-container-lowest p-6 rounded-3xl shadow-soft border border-outline-variant mb-6">
        <h4 className="font-heading text-lg font-bold mb-4 text-primary flex items-center gap-2">
          <Brain className="w-5 h-5" />
          AI Clinical Interpretation
        </h4>
        <p className="text-sm text-on-surface-variant leading-relaxed font-sans">
          {clinicalSummary}
        </p>
      </div>

      {/* ── Research Disclaimer ─────────────────────────── */}
      <div className="flex items-start gap-3 bg-slate-50 border border-slate-200 rounded-2xl p-4">
        <ShieldCheck className="w-5 h-5 text-slate-400 flex-shrink-0 mt-0.5" />
        <div>
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-0.5">
            Research Use Only
          </p>
          <p className="text-xs text-slate-400 leading-relaxed">
            This system is intended for research and educational purposes only. It should not replace
            clinical diagnosis or medical judgment. All outputs must be reviewed by a qualified
            radiologist or physician before any clinical decision is made.
          </p>
        </div>
      </div>
    </section>
  );
}
